import os
import time

def splash():
    os.system('cls' if os.name == 'nt' else 'clear')
    print('                                                                                ')
    print('                                                                                ')
    print('                                                                                ')
    print('                                                                                ')
    print('                                                                                ')
    print('                                                                                ')
    print('                                                                                ')
    print('                                                                                ')
    print('               ██████╗     ██╗    ███████╗    ██████╗     ███████╗              ')
    print('               ██╔══██╗    ╚═╝    ██╔════╝    ██╔══██╗    ██╔════╝              ')
    print('               ██████╔╝    ██╗    █████╗      ██████╔╝    ███████╗              ')
    print('               ██╔═══╝     ██║    ██╔══╝      ██╔══██╗    ╚════██║              ')
    print('               ██║         ██║    ███████╗    ██║  ██║    ███████║              ')
    print('               ╚═╝         ╚═╝    ╚══════╝    ╚═╝  ╚═╝    ╚══════╝              ')
    print('                                                                                ')
    print('                    Raspberry Pi Event Reporting System v1.0                    ')
    print('                                      BETA                                      ')
    print('                                                                                ')
    print('                                                                                ')
    print('                                                                                ')
    print('                                                                                ')
    print('                                                                                ')
    print('                  Copyright © 2017-2021  Chris Clement (K7CTC)                  ')
    time.sleep(10)

def main_menu():
    os.system('cls' if os.name == 'nt' else 'clear')
    print('                    Raspberry Pi Event Reporting System v1.0                    ')
    print('    ┌┬┐┌─┐┬┌┐┌  ┌┬┐┌─┐┌┐┌┬ ┬                                                    ')
    print('  │ │││├─┤││││  │││├┤ ││││ │ │                                                  ')
    print('╔═╡ ┴ ┴┴ ┴┴┘└┘  ┴ ┴└─┘┘└┘└─┘ ╞═════════════════════════════════════════════════╗')
    print('║                                                                              ║')
    print('║  (Q)uit                                                                      ║')
    print('║                                                                              ║')
    print('║                                                                              ║')
    print('║                                                                              ║')
    print('║                                                                              ║')
    print('║                                                                              ║')
    print('║                                                                              ║')
    print('║                                                                              ║')
    print('║                                                                              ║')
    print('║                                                                              ║')
    print('║                                                                              ║')
    print('║                                                                              ║')
    print('╚══════════════════════════════════════════════════════════════════════════════╝')

def dashboard():
    os.system('cls' if os.name == 'nt' else 'clear')
    print('                    Raspberry Pi Event Reporting System v1.0                    ')
    print('    ┌┐┌ ┌─┐ ┌┬─┐ ┌─┐   ┌─┐ ┌┬┐ ┌─┐ ┌┬┐ ┬ ┬ ┌─┐                                            ')
    print('  │ │││ │ │  │ │ ├┤    └─┐  │  ├─┤  │  │ │ └─┐ │                                          ')
    print('╔═╡ ┘└┘ └─┘ ─┴─┘ └─┘   └─┘  ┴  ┴ ┴  ┴  └─┘ └─┘ ╞═════════════════════════════════════════╗')
    print('║                                                                              ║')
    print('║                                                                              ║')
    print('╚══════════════════════════════════════════════════════════════════════════════╝')    
    print('    ┬  ┌─┐┌─┐┌┬┐┬┬┌─  ┌─┐┌┬┐┌─┐┌┬┐┬ ┬┌─┐                                        ')
    print('  │ │  │ │└─┐ │ │├┴┐  └─┐ │ ├─┤ │ │ │└─┐ │                                      ')   
    print('╔═╡ ┴─┘└─┘└─┘ ┴ ┴┴ ┴  └─┘ ┴ ┴ ┴ ┴ └─┘└─┘ ╞═════════════╤═══════════════════════╗')
    print('║ Freq: 923.300 MHz  │ BW: 125 KHz  │ TX Pwr: 20.0 mW  │ Modulation Mode: LoRa ║')
    print('╟────────────────────┴──┬───────────┴───────┬──────────┴───────────────────────╢')
    print('║ Spreading Factor: 12  │ Coding Rate: 4/8  │ Watchdog Timer Time-Out: 20 sec  ║')
    print('╚═══════════════════════╧═══════════════════╧═════════════════════════TX══▌RX▐═╝')
    
    
    print('║ Modulation Mode: LoRa  │ Watchdog Timer Time-Out: 20 seconds                 ║')
    print('╟────────────────────────┼─────────────────────────────────────────────────────╢')
    print('║ Time Scale: 1          │ Node ID: 1                                          ║')
    print('╚════════════════════════╧════════════════════════════════════════════TX══▌RX▐═╝')
    print('Press CTRL+C to quit.')
    time.sleep(15)
   


def main_menu():
    os.system('cls' if os.name == 'nt' else 'clear')
    print('                    Raspberry Pi Event Reporting System v1.0                    ')
    #print(' ██████████████████████████████████████████████████                             ')
    print('                                                                                ')
    print('╔═╡LoRa Chat TDMA LoStik Service {version}╞════════╤════════════════════╗')
    print('│ 4                                                                            │')
    print('│ 5                                                                            │')
    print('│ 6                                                                            │')
    print('│ 7                                                                            │')
    print('│ 8                                                                            │')
    print('│ 9                                                                            │')
    print('│ 10                                                                           │')
    print('│ 11                                                                           │')
    print('│ 12                                                                           │')
    print('│ 13                                                                           │')
    print('│ 14                                                                           │')
    print('│ 15                                                                           │')
    print('│ 16                                                                           │')
    print('│ 17                                                                           │')
    print('│ 18                                                                           │')
    print('│ 19                                                                           │')
    print('│ 20                                                                           │')
    print('└──────────────────────────────────────────────────────────────────────────────┘')
    print('                                                                                ')
    input('Test: ')
    
splash()
dashboard()
